import { NextResponse } from 'next/server';
import { readSession } from '../../../../lib/session';
import { getSheets } from '../../../../lib/google';
import { listAllPgs } from '../../../../lib/pgs';
import { listRooms } from '../../../../lib/rooms';
import { readRows } from '../../../../lib/plus-store';
const clean=v=>String(v??'').trim();
const mapUsers=row=>({id:row[0]||'',name:row[1]||'',mobile:row[2]||'',username:row[3]||'',role:row[5]||'',status:row[6]||'',createdAt:row[7]||'',email:row[8]||''});
const mapBooking=r=>({id:r[0]||'',customerId:r[1]||'',pgId:r[2]||'',roomId:r[3]||'',checkIn:r[4]||'',checkOut:r[5]||'',amount:Number(r[6]||0),status:r[7]||'',createdAt:r[8]||''});
const mapPay=r=>({id:r[0]||'',bookingId:r[1]||'',customerId:r[2]||'',amount:Number(r[3]||0),status:r[7]||r[6]||'',createdAt:r[8]||r[7]||''});
export async function GET(){
 try{const u=await readSession();if(!u||u.role!=='admin')return NextResponse.json({ok:false,error:'Admin only'},{status:403});const s=await getSheets();const sheetId=process.env.GOOGLE_SHEET_ID;const safe=async(range)=>{try{return (await s.spreadsheets.values.get({spreadsheetId:sheetId,range})).data.values||[]}catch{return []}};const [usersRows,bookingRows,paymentRows,refundRows,pgs,rooms,tickets,reviews,interactions,audit,verification]=await Promise.all([safe('Users!A2:I'),safe('Bookings!A2:L'),safe('Payments!A2:K'),safe('Refunds!A2:Z'),listAllPgs(false),listRooms(),readRows('SupportTickets'),readRows('Reviews'),readRows('SupportInteractions'),readRows('AdminAudit'),readRows('UserVerification')]);const users=usersRows.map(mapUsers),bookings=bookingRows.map(mapBooking).reverse(),payments=paymentRows.map(mapPay).reverse();const refunds=refundRows.map(r=>({id:r[0]||'',bookingId:r[1]||'',amount:Number(r[4]||r[3]||0),status:r[6]||r[5]||'',createdAt:r[7]||''})).reverse();return NextResponse.json({ok:true,users,pgs,rooms,bookings,payments,refunds,tickets:tickets.sort((a,b)=>Date.parse(b.created_at||0)-Date.parse(a.created_at||0)),reviews:reviews.sort((a,b)=>Date.parse(b.created_at||0)-Date.parse(a.created_at||0)),interactions:interactions.sort((a,b)=>Date.parse(b.created_at||0)-Date.parse(a.created_at||0)),audit:audit.sort((a,b)=>Date.parse(b.created_at||0)-Date.parse(a.created_at||0)),stats:{users:users.length,hosts:users.filter(x=>clean(x.role).toLowerCase()==='owner').length,guests:users.filter(x=>clean(x.role).toLowerCase()==='customer').length,properties:pgs.length,activePgs:pgs.filter(x=>!['Inactive','Disabled','Rejected'].includes(clean(x.status||x.approvalStatus))).length,bookings:bookings.length,activeBookings:bookings.filter(x=>!['Cancelled','Rejected','Completed','Checked Out'].includes(clean(x.status))).length,pending:bookings.filter(x=>x.status==='Pending').length,pendingVerification:verification.filter(x=>x.status==='Pending').length,pendingRefunds:refunds.filter(x=>!['Refunded','Rejected','Cancelled'].includes(clean(x.status))).length,todayActivity:[...audit.map(x=>x.created_at),...bookings.map(x=>x.createdAt),...payments.map(x=>x.createdAt),...refunds.map(x=>x.createdAt)].filter(v=>{const d=new Date(v);const n=new Date();return !Number.isNaN(d.getTime())&&d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()&&d.getDate()===n.getDate()}).length,openTickets:tickets.filter(x=>x.status!=='Resolved').length,payments:payments.reduce((s,x)=>s+x.amount,0)}});}catch(e){console.error('ADMIN_SUMMARY_ERROR',e);return NextResponse.json({ok:false,error:e.message},{status:500});}
}
