import { NextResponse } from 'next/server';
import { readSession } from '../../../../lib/session';
import { appendRow, readRows } from '../../../../lib/plus-store';
import { listCustomerBookings, listOwnerBookings } from '../../../../lib/bookings';
import { mailChatMessage } from '../../../../lib/lifecycle-mail';
const clean=v=>String(v??'').trim();
async function allowed(u,bid){const list=u.role==='customer'?await listCustomerBookings(u.sub):u.role==='owner'?await listOwnerBookings(u.sub):[];return list.find(x=>x.id===bid&&['Accepted','Confirmed','Refund Pending','Refund Sent'].includes(x.status));}
export async function GET(req){try{const u=await readSession();if(!u)return NextResponse.json({ok:false,error:'Unauthorized'},{status:401});const bid=clean(new URL(req.url).searchParams.get('bookingId'));if(!bid||!(await allowed(u,bid)))return NextResponse.json({ok:false,error:'Chat unavailable for this booking.'},{status:403});const rows=(await readRows('Messages')).filter(x=>x.booking_id===bid).sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at));return NextResponse.json({ok:true,messages:rows});}catch(e){return NextResponse.json({ok:false,error:e.message},{status:500});}}
export async function POST(req){try{const u=await readSession();if(!u)return NextResponse.json({ok:false,error:'Unauthorized'},{status:401});const b=await req.json(),bid=clean(b.bookingId),msg=clean(b.message);if(!bid||!(await allowed(u,bid)))return NextResponse.json({ok:false,error:'Chat unavailable for this booking.'},{status:403});if(msg.length<1||msg.length>1000)throw new Error('Message must be 1-1000 characters.');const row={id:`MSG-${Date.now().toString(36).toUpperCase()}`,booking_id:bid,sender_id:clean(u.sub),sender_role:u.role,message:msg,created_at:new Date().toISOString()};await appendRow('Messages',row);mailChatMessage(u.sub,bid,msg).catch(e=>console.error('CHAT_MAIL_ERROR',e));return NextResponse.json({ok:true,message:row},{status:201});}catch(e){return NextResponse.json({ok:false,error:e.message},{status:400});}}
