import { NextResponse } from 'next/server';
import { readSession } from '../../../../lib/session';
import { getSheets } from '../../../../lib/google';
import bcrypt from 'bcryptjs';
import { findUserById } from '../../../../lib/users';
import { notifyUser } from '../../../../lib/mailer';
import { readRows, audit } from '../../../../lib/plus-store';
import { reviewProperty, reviewVerification, resolveRiskFlag, upsertPolicy, scanRiskFlags } from '../../../../lib/platform-controls';

const clean=v=>String(v??'').trim();
async function admin(){const u=await readSession();return u?.role==='admin'?u:null;}
async function rowIndexForUser(userId){const s=await getSheets();const r=await s.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:'Users!A2:I'});const rows=r.data.values||[];return {s,rows,idx:rows.findIndex(x=>clean(x[0])===clean(userId))};}
export async function GET(){try{const u=await admin();if(!u)return NextResponse.json({ok:false,error:'Admin only'},{status:403});const [moderation,verification,risks,policies,lifecycle,locks]=await Promise.all([readRows('PropertyModeration'),readRows('UserVerification'),readRows('RiskFlags'),readRows('CancellationPolicies'),readRows('StayLifecycle'),readRows('InventoryLocks')]);return NextResponse.json({ok:true,moderation,verification,risks,policies,lifecycle,locks});}catch(e){return NextResponse.json({ok:false,error:e.message},{status:500});}}
export async function PATCH(req){try{const u=await admin();if(!u)return NextResponse.json({ok:false,error:'Admin only'},{status:403});const b=await req.json();const action=clean(b.action);
 if(action==='user-status'){const {s,rows,idx}=await rowIndexForUser(b.userId);if(idx<0)throw new Error('User not found.');const status=b.status==='Active'?'Active':'Disabled';await s.spreadsheets.values.update({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:`Users!G${idx+2}`,valueInputOption:'RAW',requestBody:{values:[[status]]}});await audit(u.sub,'USER_STATUS','User',b.userId,status);return NextResponse.json({ok:true,status});}
 if(action==='user-reset'){const user=await findUserById(b.userId);if(!user)throw new Error('User not found.');const temp=clean(b.password)||`SF@${Math.random().toString(36).slice(2,8).toUpperCase()}9`;const {s,idx}=await rowIndexForUser(b.userId);const hash=await bcrypt.hash(temp,12);await s.spreadsheets.values.update({spreadsheetId:process.env.GOOGLE_SHEET_ID,range:`Users!E${idx+2}`,valueInputOption:'RAW',requestBody:{values:[[hash]]}});await notifyUser(user,{subject:'StayFinder temporary password',title:'Your password was reset by support',lines:[`Username: ${user.username}`,`Temporary password: ${temp}`,'Please sign in and use Forgot Password if you want to set another password.']});await audit(u.sub,'PASSWORD_RESET','User',b.userId,'Temporary password issued');return NextResponse.json({ok:true,tempPassword:temp});}
 if(action==='property-review'){const item=await reviewProperty(u.sub,b.pgId,b.status,b.note);await audit(u.sub,'PROPERTY_REVIEW','Property',b.pgId,`${b.status}: ${clean(b.note)}`);return NextResponse.json({ok:true,item});}
 if(action==='verification-review'){const item=await reviewVerification(u.sub,b.id,b.status,b.note);await audit(u.sub,'VERIFICATION_REVIEW','Verification',b.id,`${b.status}: ${clean(b.note)}`);return NextResponse.json({ok:true,item});}
 if(action==='risk-resolve'){const item=await resolveRiskFlag(u.sub,b.id);await audit(u.sub,'RISK_RESOLVED','Risk',b.id,'Resolved');return NextResponse.json({ok:true,item});}
 if(action==='policy-save'){const item=await upsertPolicy(u.sub,b);await audit(u.sub,'POLICY_SAVE','CancellationPolicy',item.id,item.name);return NextResponse.json({ok:true,item});}
 throw new Error('Invalid admin action.');
 }catch(e){return NextResponse.json({ok:false,error:e.message},{status:400});}}
export async function POST(req){try{const u=await admin();if(!u)return NextResponse.json({ok:false,error:'Admin only'},{status:403});const b=await req.json();if(b.action!=='risk-scan')throw new Error('Invalid admin action.');const s=await getSheets();const safe=async range=>{try{return (await s.spreadsheets.values.get({spreadsheetId:process.env.GOOGLE_SHEET_ID,range})).data.values||[]}catch{return []}};const [ur,br,pr]=await Promise.all([safe('Users!A2:I'),safe('Bookings!A2:L'),safe('Payments!A2:K')]);const users=ur.map(r=>({id:r[0],mobile:r[2],email:r[8]})),bookings=br.map(r=>({id:r[0],customerId:r[1],status:r[7]})),payments=pr.map(r=>({id:r[0],transactionRef:r[4]||''}));const risks=await scanRiskFlags({users,bookings,payments});await audit(u.sub,'RISK_SCAN','System','all',`${risks.filter(x=>x.status!=='Resolved').length} open flags`);return NextResponse.json({ok:true,risks});}catch(e){return NextResponse.json({ok:false,error:e.message},{status:400});}}
