import { NextResponse } from 'next/server';
import { readSession } from '../../../../lib/session';
import { appendRow, readRows, updateRow } from '../../../../lib/plus-store';
import { listCustomerBookings } from '../../../../lib/bookings';
import { listPgsByOwner } from '../../../../lib/pgs';
const clean=v=>String(v??'').trim(); const num=v=>Math.max(1,Math.min(5,Number(v||0)));
async function completedIds(customerId){const bookings=await listCustomerBookings(customerId);const mine=new Set(bookings.map(x=>x.id));const stays=await readRows('StayLifecycle');return new Set(stays.filter(x=>mine.has(x.booking_id)&&clean(x.checkout_verified_at)).map(x=>x.booking_id));}
export async function GET(req){try{const u=await readSession();if(!u)return NextResponse.json({ok:false,error:'Unauthorized'},{status:401});const url=new URL(req.url);let rows=await readRows('Reviews');const pgId=clean(url.searchParams.get('pgId'));if(pgId)rows=rows.filter(x=>x.pg_id===pgId&&x.status!=='Hidden');let eligibleBookingIds=[];if(u.role==='customer'&&!pgId){rows=rows.filter(x=>x.customer_id===clean(u.sub));eligibleBookingIds=[...(await completedIds(u.sub))];}else if(u.role==='owner'&&!pgId){const ids=new Set((await listPgsByOwner(u.sub)).map(x=>x.id));rows=rows.filter(x=>ids.has(x.pg_id));}return NextResponse.json({ok:true,reviews:rows,eligibleBookingIds});}catch(e){return NextResponse.json({ok:false,error:e.message},{status:500});}}
export async function POST(req){try{const u=await readSession();if(!u||u.role!=='customer')return NextResponse.json({ok:false,error:'Customer only'},{status:403});const b=await req.json();const bookings=await listCustomerBookings(u.sub);const bk=bookings.find(x=>x.id===clean(b.bookingId));if(!bk)throw new Error('Booking not found.');const eligible=await completedIds(u.sub);if(!eligible.has(bk.id))throw new Error('Review can be submitted only after checkout is completed.');const rows=await readRows('Reviews');if(rows.some(x=>x.booking_id===bk.id&&x.customer_id===clean(u.sub)))throw new Error('Review already submitted for this booking.');const row={id:`REV-${Date.now().toString(36).toUpperCase()}`,booking_id:bk.id,pg_id:bk.pgId,customer_id:clean(u.sub),rating:num(b.rating),cleanliness:num(b.cleanliness||b.rating),food:num(b.food||b.rating),location:num(b.location||b.rating),host_behaviour:num(b.hostBehaviour||b.rating),value_for_money:num(b.valueForMoney||b.rating),comment:clean(b.comment),status:'Published',created_at:new Date().toISOString(),owner_reply:'',owner_replied_at:'',safety:num(b.safety||b.rating)};await appendRow('Reviews',row);return NextResponse.json({ok:true,review:row},{status:201});}catch(e){return NextResponse.json({ok:false,error:e.message},{status:400});}}
export async function PATCH(req){try{const u=await readSession();if(!u||u.role!=='owner')return NextResponse.json({ok:false,error:'Owner only'},{status:403});const b=await req.json(),reply=clean(b.reply);if(reply.length<2)throw new Error('Reply is required.');const rows=await readRows('Reviews'),review=rows.find(x=>x.id===clean(b.id));if(!review)throw new Error('Review not found.');const mine=new Set((await listPgsByOwner(u.sub)).map(x=>x.id));if(!mine.has(review.pg_id))throw new Error('This review does not belong to your property.');if(clean(review.owner_reply))throw new Error('Owner reply has already been submitted.');const item=await updateRow('Reviews',review.id,{owner_reply:reply,owner_replied_at:new Date().toISOString()});return NextResponse.json({ok:true,review:item});}catch(e){return NextResponse.json({ok:false,error:e.message},{status:400});}}
