'use client';
import { useEffect,useMemo,useState } from 'react';
const fmt=d=>{try{return new Date(d).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}catch{return d||''}};
async function req(url,opt){const r=await fetch(url,{cache:'no-store',...opt});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Request failed.');return d;}
export default function StayOperations({role,bookings=[],pgs=[]}){
 const [data,setData]=useState({modifications:[],deposits:[],promos:[],reminders:[]}),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 const [mod,setMod]=useState({bookingId:'',newCheckIn:'',newCheckOut:'',stayMonths:'',reason:''});
 const [promo,setPromo]=useState({code:'',pgId:'',discountType:'Percent',discountValue:'',expiresAt:'',maxUses:''});
 async function load(){try{setErr('');setData(await req('/api/plus/operations'));}catch(e){setErr(e.message)}}
 useEffect(()=>{load()},[]);
 async function post(body){setBusy(true);try{await req('/api/plus/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await load();return true}catch(e){setErr(e.message);return false}finally{setBusy(false)}}
 async function patch(body){setBusy(true);try{await req('/api/plus/operations',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await load();return true}catch(e){setErr(e.message);return false}finally{setBusy(false)}}
 const eligible=useMemo(()=>bookings.filter(b=>['Accepted','Confirmed'].includes(b.status)),[bookings]);
 return <div className="sfOps">{err&&<div className="sfOpsErr">{err}</div>}
  {data.reminders?.length>0&&<section><h3>Due reminders</h3>{data.reminders.slice(0,6).map(x=><article key={x.bookingId} className={x.overdue?'late':''}><b>{x.title}</b><span>₹{Number(x.amount||0).toLocaleString('en-IN')} · Due {x.dueDate}</span><small>{x.overdue?'Payment due date passed':x.daysLeft===0?'Due today':`${x.daysLeft} day(s) left`}</small></article>)}</section>}
  <section><h3>Booking modification</h3>{role==='customer'&&<form onSubmit={async e=>{e.preventDefault();if(await post({action:'modification-request',...mod}))setMod({bookingId:'',newCheckIn:'',newCheckOut:'',stayMonths:'',reason:''})}}><label>Booking<select required value={mod.bookingId} onChange={e=>setMod({...mod,bookingId:e.target.value})}><option value="">Select booking</option>{eligible.map(b=><option key={b.id} value={b.id}>{b.id} · {b.pg?.name||b.pgId}</option>)}</select></label><div className="sfOpsGrid"><label>New check-in<input type="date" value={mod.newCheckIn} onChange={e=>setMod({...mod,newCheckIn:e.target.value})}/></label><label>New check-out<input type="date" value={mod.newCheckOut} onChange={e=>setMod({...mod,newCheckOut:e.target.value})}/></label></div><label>Or duration (months)<input type="number" min="1" max="24" value={mod.stayMonths} onChange={e=>setMod({...mod,stayMonths:e.target.value})}/></label><label>Reason<textarea rows="2" required value={mod.reason} onChange={e=>setMod({...mod,reason:e.target.value})}/></label><button disabled={busy}>Send modification request</button></form>}
   <div className="sfOpsList">{data.modifications?.length?data.modifications.map(x=><article key={x.id}><b>{x.booking_id}</b><span>{x.old_check_in} → {x.old_check_out}</span><span>Requested: {x.new_check_in} → {x.new_check_out}</span><small>{x.status} · {fmt(x.created_at)}</small>{x.reason&&<p>{x.reason}</p>}{x.owner_note&&<p>Owner: {x.owner_note}</p>}{role==='owner'&&x.status==='Pending'&&<div className="sfOpsActions"><button onClick={()=>patch({action:'modification-review',id:x.id,status:'Approved',note:''})}>Approve</button><button className="soft" onClick={()=>{const note=prompt('Reason for rejection:','Requested dates are not available.')||'';if(note.trim())patch({action:'modification-review',id:x.id,status:'Rejected',note})}}>Reject</button></div>}</article>):<p className="emptyLine">No modification requests.</p>}</div>
  </section>
  <section><h3>Security deposit tracking</h3><div className="sfOpsList">{data.deposits?.length?data.deposits.map(x=><article key={x.id}><b>{x.booking_id} · ₹{Number(x.amount||0).toLocaleString('en-IN')}</b><span>Status: {x.status}</span>{x.adjustment_amount>0&&<span>Adjusted: ₹{Number(x.adjustment_amount).toLocaleString('en-IN')}</span>}{x.note&&<p>{x.note}</p>}{role==='owner'&&!['Refunded','Adjusted'].includes(x.status)&&<div className="sfOpsActions">{x.status==='Received'&&<button onClick={()=>patch({action:'deposit-status',id:x.id,status:'Held'})}>Mark Held</button>}<button onClick={()=>patch({action:'deposit-status',id:x.id,status:'Refunded'})}>Mark Refunded</button><button className="soft" onClick={()=>{const amount=prompt('Adjustment amount:','0');if(amount===null)return;const note=prompt('Adjustment reason:','Damage / dues adjustment')||'';if(note.trim())patch({action:'deposit-status',id:x.id,status:'Adjusted',adjustmentAmount:amount,note})}}>Adjust</button></div>}</article>):<p className="emptyLine">No security deposits yet.</p>}</div></section>
  {role==='owner'&&<section><h3>Promo / coupon codes</h3><form onSubmit={async e=>{e.preventDefault();if(await post({action:'promo-create',...promo}))setPromo({code:'',pgId:'',discountType:'Percent',discountValue:'',expiresAt:'',maxUses:''})}}><div className="sfOpsGrid"><label>Code<input required value={promo.code} onChange={e=>setPromo({...promo,code:e.target.value.toUpperCase()})} placeholder="WELCOME10"/></label><label>Property<select value={promo.pgId} onChange={e=>setPromo({...promo,pgId:e.target.value})}><option value="">All my PGs</option>{pgs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Discount<select value={promo.discountType} onChange={e=>setPromo({...promo,discountType:e.target.value})}><option>Percent</option><option>Fixed</option></select></label><label>Value<input required type="number" min="1" value={promo.discountValue} onChange={e=>setPromo({...promo,discountValue:e.target.value})}/></label><label>Expiry<input type="date" value={promo.expiresAt} onChange={e=>setPromo({...promo,expiresAt:e.target.value})}/></label><label>Usage limit<input type="number" min="0" value={promo.maxUses} onChange={e=>setPromo({...promo,maxUses:e.target.value})}/></label></div><button disabled={busy}>Create coupon</button></form><div className="sfOpsList">{data.promos?.map(x=><article key={x.id}><b>{x.code} · {x.discount_type==='Fixed'?`₹${x.discount_value}`:`${x.discount_value}%`} off</b><span>{x.pg_id||'All properties'} · Used {x.used_count||0}{Number(x.max_uses)>0?`/${x.max_uses}`:''}</span><small>{x.status}{x.expires_at?` · Expires ${x.expires_at}`:''}</small></article>)}</div></section>}
  <style>{`.sfOps{display:grid;gap:12px}.sfOps>section{background:#fff;border:1px solid #dce8e6;border-radius:16px;padding:13px;display:grid;gap:10px}.sfOps h3{margin:0;color:#173f3d}.sfOps form{display:grid;gap:8px}.sfOps label{display:grid;gap:4px;font-size:10px;font-weight:800;color:#506b68}.sfOps input,.sfOps select,.sfOps textarea{width:100%;box-sizing:border-box;border:1px solid #d6e4e2;border-radius:10px;padding:9px;background:#fff;font:inherit}.sfOps button{border:0;background:#1f665f;color:#fff;border-radius:10px;min-height:38px;padding:0 12px;font-weight:900}.sfOpsGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.sfOpsList{display:grid;gap:7px}.sfOpsList article,.sfOps>section>article{border:1px solid #e1eae8;border-radius:12px;padding:10px;display:grid;gap:3px}.sfOpsList b,.sfOpsList span,.sfOpsList small{display:block}.sfOpsList span{font-size:10px;color:#526e6b}.sfOpsList small{font-size:9px;color:#7a8d8a}.sfOpsList p{font-size:10px;margin:3px 0}.sfOpsActions{display:flex;gap:6px;margin-top:5px}.sfOpsActions .soft{background:#edf4f3;color:#275854}.sfOpsErr{background:#fff0f0;color:#9a3c3c;border-radius:10px;padding:9px}.late{background:#fff5f2}.emptyLine{font-size:10px;color:#738481}@media(max-width:620px){.sfOpsGrid{grid-template-columns:1fr}}`}</style>
 </div>;
}
