import { NextResponse } from 'next/server';
import { readSession } from '../../../../lib/session';
import { listCustomerBookings, listOwnerBookings } from '../../../../lib/bookings';
import { createPromo,listPromosFor,createModification,modificationRows,reviewModification,syncDeposits,updateDeposit,dueReminders } from '../../../../lib/booking-enhancements';
const clean=v=>String(v??'').trim();
async function mine(u){return u.role==='owner'?listOwnerBookings(u.sub):u.role==='customer'?listCustomerBookings(u.sub):[];}
export async function GET(){try{const u=await readSession();if(!u)return NextResponse.json({ok:false,error:'Unauthorized'},{status:401});const bookings=await mine(u);const [modifications,deposits,promos]=await Promise.all([modificationRows(u,bookings),syncDeposits(bookings),listPromosFor(u)]);return NextResponse.json({ok:true,modifications,deposits,promos,reminders:dueReminders(bookings)});}catch(e){return NextResponse.json({ok:false,error:e.message},{status:500});}}
export async function POST(req){try{const u=await readSession();if(!u)return NextResponse.json({ok:false,error:'Unauthorized'},{status:401});const b=await req.json();const action=clean(b.action);if(action==='modification-request')return NextResponse.json({ok:true,item:await createModification(u,b)},{status:201});if(action==='promo-create')return NextResponse.json({ok:true,item:await createPromo(u,b)},{status:201});throw new Error('Invalid action.');}catch(e){return NextResponse.json({ok:false,error:e.message},{status:400});}}
export async function PATCH(req){try{const u=await readSession();if(!u)return NextResponse.json({ok:false,error:'Unauthorized'},{status:401});const b=await req.json(),bookings=await mine(u),action=clean(b.action);if(action==='modification-review')return NextResponse.json({ok:true,item:await reviewModification(u,b,bookings)});if(action==='deposit-status')return NextResponse.json({ok:true,item:await updateDeposit(u,b,bookings)});throw new Error('Invalid action.');}catch(e){return NextResponse.json({ok:false,error:e.message},{status:400});}}
